spring:
  datasource:
    url: jdbc:mysql://db:3306/ccm
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:https://github.com/CampusCalenderManager/CCM_Back/blob/main/ccm/application-local.yml
      ddl-auto: create-drop

    show_sql: true
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  http:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
