version: "3"
services:
    db:
        container_name: spring-db
        image: mysql:8
        environment:
            - MYSQL_DATABASE=ccm
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASSWORD
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 3s
            timeout: 10s
            retries: 500
    app:
        container_name: ccm-app
        build: .
        environment:
          - DB_USER
          - DB_PASSWORD
          - DB_HOST
          - JWT_SECRET
          - JWT_EXPIRATION
        depends_on:
          db:
            condition: service_healthy
        ports:
                - 80:8080
        restart: always
