version: "3"
services:
    db:
        container_name: spring-db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ccm
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        command: [--ignore-db-dir=lost+found]
        restart: always
    app:
        container_name: ccm-app
        build: .
        depends_on:
            - db
        ports:
                - 80:8080
        restart: always
